services:
  - type: web
    name: car-budget-app
    env: python
    plan: free
    buildCommand: "poetry install"
    startCommand: "gunicorn main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
