services:
  - type: web
    name: car-budget-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    # ✅ This is important
    workingDir: .

